<?php


declare(strict_types=1);

const LICENSE_EXPIRY = '2026-10-01 00:00:00';
const DEVELOPER_NAME = 'Mohammed omer elsamani';
const DEVELOPER_SITE = 'https://elsamanii.rf.gd';
const DEVELOPER_PHONE = '0127941569';

// إذا كان config.php في نفس مجلد الملف اتركه كما هو.
const CONFIG_FILE = __DIR__ . '/config/config.php';

// -------------------------
// إعدادات عامة
// -------------------------
function lm_base_dir(): string {
    return dirname(__DIR__);
}

function lm_storage_dir(): string {
    // يفضّل التخزين خارج public_html.
    $parent = dirname(__DIR__);
    $dir = $parent . DIRECTORY_SEPARATOR . '.system_backups';
    if (!is_dir($dir)) {
        @mkdir($dir, 0700, true);
    }
    return $dir;
}

function lm_license_file(): string {
    return lm_storage_dir() . DIRECTORY_SEPARATOR . '.license.dat';
}

function lm_secret(): string {
    // المفتاح يُشتق من معلومات السيرفر + مسار التطبيق.
    // غيّره إلى قيمة سرية طويلة خاصة بك لزيادة قوة الحماية.
    return hash('sha256', __DIR__ . '|' . PHP_VERSION . '|' . 'Mohammed-Omer-Elsamani-License-2026', true);
}

function lm_load_config(): bool {
    if (!is_file(CONFIG_FILE)) {
        return false;
    }
    require_once CONFIG_FILE;
    return isset($GLOBALS['mysqli']) && $GLOBALS['mysqli'] instanceof mysqli;
}

function lm_escape(string $value): string {
    return str_replace(
        ["\\", "\0", "\n", "\r", "'", '"', "\x1a"],
        ["\\\\", "\\0", "\\n", "\\r", "\\'", '\\"', "\\Z"],
        $value
    );
}

function lm_sql_dump(mysqli $db): string {
    $sql = "-- Database backup generated by license_backup_manager.php\n";
    $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
    $sql .= "SET FOREIGN_KEY_CHECKS=0;\nSET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\n\n";

    $tables = [];
    $result = $db->query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
    if (!$result) {
        throw new RuntimeException('Unable to list database tables: ' . $db->error);
    }

    while ($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }
    $result->free();

    foreach ($tables as $table) {
        $safeTable = str_replace('`', '``', $table);
        $create = $db->query("SHOW CREATE TABLE `{$safeTable}`");
        if (!$create) {
            continue;
        }
        $createRow = $create->fetch_assoc();
        $createSql = $createRow['Create Table'] ?? '';
        $create->free();

        $sql .= "DROP TABLE IF EXISTS `{$safeTable}`;\n";
        $sql .= $createSql . ";\n\n";

        $data = $db->query("SELECT * FROM `{$safeTable}`");
        if ($data && $data->num_rows > 0) {
            $fields = [];
            $fieldResult = $db->query("SHOW COLUMNS FROM `{$safeTable}`");
            while ($f = $fieldResult->fetch_assoc()) {
                $fields[] = '`' . str_replace('`', '``', $f['Field']) . '`';
            }
            $fieldResult->free();

            $sql .= "INSERT INTO `{$safeTable}` (" . implode(',', $fields) . ") VALUES\n";
            $rows = [];
            while ($record = $data->fetch_assoc()) {
                $vals = [];
                foreach ($fields as $field) {
                    $name = trim($field, '`');
                    $value = $record[$name] ?? null;
                    $vals[] = $value === null ? 'NULL' : "'" . lm_escape((string)$value) . "'";
                }
                $rows[] = '(' . implode(',', $vals) . ')';
            }
            $sql .= implode(",\n", $rows) . ";\n\n";
            $data->free();
        }
    }

    $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
    return $sql;
}

function lm_make_daily_backup(): array {
    static $done = false;
    if ($done) return ['success' => true, 'skipped' => true];
    $done = true;

    if (!lm_load_config()) {
        return ['success' => false, 'error' => 'config.php / mysqli connection not available'];
    }

    $dir = lm_storage_dir();
    if (!is_dir($dir) && !@mkdir($dir, 0700, true)) {
        return ['success' => false, 'error' => 'Cannot create backup directory'];
    }

    // ملف صغير لمعرفة آخر يوم تم فيه النسخ.
    $marker = $dir . DIRECTORY_SEPARATOR . '.last_backup_date';
    $today = date('Y-m-d');

    if (is_file($marker) && trim((string)@file_get_contents($marker)) === $today) {
        return ['success' => true, 'skipped' => true];
    }

    try {
        $sql = lm_sql_dump($GLOBALS['mysqli']);
        $filename = 'database_' . date('Y-m-d_H-i-s') . '.sql.gz';
        $path = $dir . DIRECTORY_SEPARATOR . $filename;

        $gz = @gzopen($path, 'wb9');
        if (!$gz) {
            return ['success' => false, 'error' => 'Cannot create compressed backup file'];
        }
        gzwrite($gz, $sql);
        gzclose($gz);

        @file_put_contents($marker, $today, LOCK_EX);
        @chmod($path, 0600);

        return ['success' => true, 'file' => $filename];
    } catch (Throwable $e) {
        return ['success' => false, 'error' => $e->getMessage()];
    }
}

function lm_license_payload(): ?array {
    $file = lm_license_file();
    if (!is_file($file)) return null;

    $raw = @file_get_contents($file);
    if (!$raw) return null;

    $parts = explode('.', $raw, 2);
    if (count($parts) !== 2) return null;

    [$encoded, $signature] = $parts;
    $expected = hash_hmac('sha256', $encoded, lm_secret());

    if (!hash_equals($expected, $signature)) return null;

    $json = base64_decode($encoded, true);
    if ($json === false) return null;

    $data = json_decode($json, true);
    return is_array($data) ? $data : null;
}

function lm_is_activated(): bool {
    $data = lm_license_payload();
    if (!$data || empty($data['activated_at'])) return false;

    // لا نقبل تفعيلاً بتاريخ غير منطقي مستقبلياً.
    $activatedAt = strtotime((string)$data['activated_at']);
    if (!$activatedAt || $activatedAt > time() + 300) return false;

    return true;
}

function lm_activate(string $activation_code): bool {
    // كود تفعيل يتم توليده للمشروع بواسطة المطور.
    // يمكنك تغيير هذا الكود لكل عميل.
    $validCodes = [
        'MO-2026-ELSA-RENEW'
    ];

    if (!in_array(trim($activation_code), $validCodes, true)) {
        return false;
    }

    $payload = [
        'activated_at' => date('c'),
        'developer' => DEVELOPER_NAME,
        'version' => 1
    ];

    $encoded = base64_encode(json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    $signature = hash_hmac('sha256', $encoded, lm_secret());

    $dir = lm_storage_dir();
    if (!is_dir($dir)) @mkdir($dir, 0700, true);

    $ok = @file_put_contents(lm_license_file(), $encoded . '.' . $signature, LOCK_EX) !== false;
    if ($ok) @chmod(lm_license_file(), 0600);

    return $ok;
}

function lm_force_activation(): void {
    $requestPath = parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH) ?: '';

    // لا تمنع صفحة التفعيل نفسها.
    if (basename($requestPath) === basename(__FILE__)) return;

    // لا تطبق الحاجز قبل تاريخ الانتهاء.
    if (time() < strtotime(LICENSE_EXPIRY)) return;

    if (!lm_is_activated()) {
        $target = basename(__FILE__);
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        header('Location: ' . $target . '?activate=1', true, 302);
        exit;
    }
}

// النسخ اليومي يمكن تشغيله في كل طلب، لكنه فعلياً ينشئ نسخة واحدة فقط يومياً.
lm_make_daily_backup();
lm_force_activation();

$activated = lm_is_activated();
$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['activation_code'])) {
    $code = trim((string)$_POST['activation_code']);
    if (lm_activate($code)) {
        $activated = true;
        $message = 'تم تنشيط الاشتراك بنجاح. شكراً لاستخدام النظام.';
    } else {
        $error = 'رمز التنشيط غير صحيح. يرجى التواصل مع المطور لتجديد الاشتراك.';
    }
}
?>
<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>تجديد الاشتراك | <?php echo htmlspecialchars(DEVELOPER_NAME); ?></title>
<style>
*{box-sizing:border-box}
body{
    margin:0;min-height:100vh;font-family:Tahoma,Arial,sans-serif;
    background:radial-gradient(circle at top,#162b48 0,#08111f 55%,#04080f 100%);
    color:#fff;display:flex;align-items:center;justify-content:center;padding:25px;
}
.card{
    width:min(680px,100%);background:rgba(255,255,255,.07);
    border:1px solid rgba(255,255,255,.12);border-radius:28px;
    box-shadow:0 25px 80px rgba(0,0,0,.45);padding:42px;
    backdrop-filter:blur(18px);text-align:center;
}
.icon{
    width:92px;height:92px;margin:0 auto 22px;border-radius:50%;
    display:grid;place-items:center;background:linear-gradient(135deg,#0d6efd,#00c6ff);
    font-size:42px;box-shadow:0 12px 35px rgba(0,198,255,.25);
}
h1{margin:0 0 12px;font-size:31px}
p{color:#c9d6e8;line-height:1.9;margin:8px 0}
.expiry{display:inline-block;margin:18px 0;padding:10px 18px;border-radius:999px;
    background:rgba(255,193,7,.13);color:#ffd166;border:1px solid rgba(255,209,102,.3)}
input{
    width:100%;padding:16px 18px;border-radius:14px;border:1px solid #40536c;
    background:#07101c;color:#fff;font-size:17px;outline:none;text-align:center;
}
input:focus{border-color:#00c6ff;box-shadow:0 0 0 3px rgba(0,198,255,.12)}
button{
    width:100%;margin-top:14px;padding:16px;border:0;border-radius:14px;
    background:linear-gradient(135deg,#0d6efd,#00b8ff);color:#fff;
    font-size:17px;font-weight:bold;cursor:pointer;
}
.alert{margin:15px 0;padding:13px;border-radius:12px}
.err{background:rgba(220,53,69,.14);border:1px solid rgba(220,53,69,.35);color:#ff9ca7}
.ok{background:rgba(25,135,84,.14);border:1px solid rgba(25,135,84,.35);color:#8df0bc}
.footer{margin-top:28px;padding-top:20px;border-top:1px solid rgba(255,255,255,.1);font-size:14px}
a{color:#6edcff;text-decoration:none}
.small{font-size:13px;color:#8ea3bd}
</style>
</head>
<body>
<div class="card">
    <div class="icon">🔐</div>

    <?php if ($activated): ?>
        <h1>تم تنشيط النظام بنجاح</h1>
        <p>الاشتراك مفعل ويمكنك العودة إلى النظام ومتابعة العمل بصورة طبيعية.</p>
        <?php if ($message): ?><div class="alert ok"><?php echo htmlspecialchars($message); ?></div><?php endif; ?>
        <button type="button" onclick="history.back()">العودة للنظام</button>
    <?php else: ?>
        <h1>تجديد اشتراك النظام</h1>
        <p>
            انتهت مدة الاشتراك الحالية. للاستمرار في استخدام النظام يجب تنشيط الاشتراك.
            لا يمكن تجاوز صفحة التنشيط قبل إدخال رمز صالح.
        </p>
        <div class="expiry">تاريخ انتهاء الاشتراك: 01 أكتوبر 2026</div>

        <?php if ($error): ?><div class="alert err"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>

        <form method="post" autocomplete="off">
            <input type="text" name="activation_code"
                   placeholder="أدخل رمز التنشيط"
                   required autofocus>
            <button type="submit">تنشيط الاشتراك الآن</button>
        </form>

        <p class="small">للحصول على رمز التجديد، يرجى التواصل مع المطور.</p>
    <?php endif; ?>

    <div class="footer">
        <strong>المطور: <?php echo htmlspecialchars(DEVELOPER_NAME); ?></strong><br>
        الموقع:
        <a href="<?php echo htmlspecialchars(DEVELOPER_SITE); ?>" target="_blank" rel="noopener">
            <?php echo htmlspecialchars(DEVELOPER_SITE); ?>
        </a><br>
        الهاتف: <?php echo htmlspecialchars(DEVELOPER_PHONE); ?>
    </div>
</div>
</body>
</html>
